/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AgentAssignment } from "./AgentAssignment";
import { AgentAssignmentCountArgs } from "./AgentAssignmentCountArgs";
import { AgentAssignmentFindManyArgs } from "./AgentAssignmentFindManyArgs";
import { AgentAssignmentFindUniqueArgs } from "./AgentAssignmentFindUniqueArgs";
import { CreateAgentAssignmentArgs } from "./CreateAgentAssignmentArgs";
import { UpdateAgentAssignmentArgs } from "./UpdateAgentAssignmentArgs";
import { DeleteAgentAssignmentArgs } from "./DeleteAgentAssignmentArgs";
import { Property } from "../../property/base/Property";
import { AgentAssignmentService } from "../agentAssignment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AgentAssignment)
export class AgentAssignmentResolverBase {
  constructor(
    protected readonly service: AgentAssignmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AgentAssignment",
    action: "read",
    possession: "any",
  })
  async _agentAssignmentsMeta(
    @graphql.Args() args: AgentAssignmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AgentAssignment])
  @nestAccessControl.UseRoles({
    resource: "AgentAssignment",
    action: "read",
    possession: "any",
  })
  async agentAssignments(
    @graphql.Args() args: AgentAssignmentFindManyArgs
  ): Promise<AgentAssignment[]> {
    return this.service.agentAssignments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AgentAssignment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AgentAssignment",
    action: "read",
    possession: "own",
  })
  async agentAssignment(
    @graphql.Args() args: AgentAssignmentFindUniqueArgs
  ): Promise<AgentAssignment | null> {
    const result = await this.service.agentAssignment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AgentAssignment)
  @nestAccessControl.UseRoles({
    resource: "AgentAssignment",
    action: "create",
    possession: "any",
  })
  async createAgentAssignment(
    @graphql.Args() args: CreateAgentAssignmentArgs
  ): Promise<AgentAssignment> {
    return await this.service.createAgentAssignment({
      ...args,
      data: {
        ...args.data,

        property: args.data.property
          ? {
              connect: args.data.property,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AgentAssignment)
  @nestAccessControl.UseRoles({
    resource: "AgentAssignment",
    action: "update",
    possession: "any",
  })
  async updateAgentAssignment(
    @graphql.Args() args: UpdateAgentAssignmentArgs
  ): Promise<AgentAssignment | null> {
    try {
      return await this.service.updateAgentAssignment({
        ...args,
        data: {
          ...args.data,

          property: args.data.property
            ? {
                connect: args.data.property,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AgentAssignment)
  @nestAccessControl.UseRoles({
    resource: "AgentAssignment",
    action: "delete",
    possession: "any",
  })
  async deleteAgentAssignment(
    @graphql.Args() args: DeleteAgentAssignmentArgs
  ): Promise<AgentAssignment | null> {
    try {
      return await this.service.deleteAgentAssignment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Property, {
    nullable: true,
    name: "property",
  })
  @nestAccessControl.UseRoles({
    resource: "Property",
    action: "read",
    possession: "any",
  })
  async getProperty(
    @graphql.Parent() parent: AgentAssignment
  ): Promise<Property | null> {
    const result = await this.service.getProperty(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
